parameters:
#    dlv_website.example.class: DLV\WebsiteBundle\Example

services:
#    dlv_website.example:
#        class: %dlv_website.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
